/** HORNYS-POS V3 — contract-level quotas, tracked per employee. */
var ContractQuotaServiceV3 = (function () {
  'use strict';
  var HEADERS = ['ID','Contract ID','Article ID','Active','Quota','Period','Created At','Updated At'];
  function sheet_(){return assurerFeuilleAvecEntetes('CONTRACT_ARTICLE_QUOTAS',HEADERS);}
  function normPeriod_(value){var p=String(value||'DAY').trim().toUpperCase();if(p==='JOUR'||p==='DAILY')return'DAY';if(p==='SEMAINE'||p==='WEEKLY')return'WEEK';return p==='WEEK'?'WEEK':'DAY';}
  function rows_(){var s=sheet_();if(s.getLastRow()<2)return[];return s.getRange(2,1,s.getLastRow()-1,HEADERS.length).getValues();}
  function list(contractId){return rows_().filter(function(r){return String(r[1])===String(contractId);}).map(function(r){return{id:r[0],contractId:r[1],articleId:r[2],active:r[3]===true||String(r[3]).toUpperCase()==='TRUE',quota:Number(r[4])||0,period:normPeriod_(r[5]),createdAt:r[6],updatedAt:r[7]};});}
  function save(contractId,rules,vendeurId){if(vendeurId)verifierPermission(vendeurId,'contrats');if(!contractId)throw new Error('Le contrat est obligatoire.');var contract=contratsEntreprises().find(function(c){return String(c.id)===String(contractId);});if(!contract)throw new Error('Contrat introuvable.');var sheet=sheet_(),existing=rows_(),now=new Date(),incoming=Array.isArray(rules)?rules:[];var keep=incoming.filter(Boolean).map(function(r){var quota=Number(r.quota);if(!Number.isFinite(quota)||quota<0)throw new Error('Chaque quota doit être un nombre positif ou nul.');return{articleId:String(r.articleId||'').trim(),active:r.active!==false,quota:Math.floor(quota),period:normPeriod_(r.period)};}).filter(function(r){return r.articleId;});var seen={};keep.forEach(function(r){if(seen[r.articleId])throw new Error('Un article ne peut avoir qu’un quota par contrat.');seen[r.articleId]=true;});var rowsToDelete=[];existing.forEach(function(r,i){if(String(r[1])===String(contractId))rowsToDelete.push(i+2);});rowsToDelete.reverse().forEach(function(n){sheet.deleteRow(n);});keep.forEach(function(r){sheet.appendRow([prochainIdentifiant(sheet,'CQA',now.getFullYear()),contractId,r.articleId,r.active,r.quota,r.period,now,now]);});return list(contractId);}
  function getRule(rules,contractId,articleId){var found=(rules||[]).find(function(r){return String(r.contractId)===String(contractId)&&String(r.articleId)===String(articleId)&&r.active!==false;});return found?{quota:Number(found.quota)||0,period:normPeriod_(found.period)}:null;}
  function periodStart_(now,period){var d=new Date(now.getFullYear(),now.getMonth(),now.getDate());if(period==='WEEK'){var day=d.getDay()||7;d.setDate(d.getDate()-day+1);}return d;}
  function consumed(contractId,employeeId,articleId,period,now){var start=periodStart_(now||new Date(),normPeriod_(period)),sheet=obtenirFeuille('CONTRACT_TRANSACTIONS');if(!sheet||sheet.getLastRow()<2)return 0;var rows=sheet.getRange(2,1,sheet.getLastRow()-1,Math.min(18,sheet.getLastColumn())).getValues();return rows.reduce(function(total,row){if(String(row[1])!==String(contractId)||String(row[3])!==String(employeeId)||!(row[15] instanceof Date)||row[15]<start)return total;var articles=[];try{articles=JSON.parse(row[14]||'[]');}catch(e){}var item=articles.find(function(a){return String(a.id)===String(articleId);});return total+(item?Number(item.quantity)||0:0);},0);}
  function validate(contract,employee,articles,now){var rules=list(contract.id).filter(function(r){return r.active;});if(!rules.length)return true;articles.forEach(function(article){var rule=getRule(rules,contract.id,article.id);if(!rule)throw new Error('L’article "'+article.nom+'" n’est pas pris en charge par ce contrat.');var used=consumed(contract.id,employee.id,article.id,rule.period,now),requested=Number(article.quantity)||0;if(used+requested>rule.quota){var label=rule.period==='WEEK'?'cette semaine':'aujourd’hui';throw new Error('Quota atteint pour "'+article.nom+'" pour '+employee.name+': '+used+'/'+rule.quota+' utilisé(s) '+label+'.');}});return true;}
  function overview(contractId,employeeId){var now=new Date();return list(contractId).filter(function(r){return r.active;}).map(function(r){var used=consumed(contractId,employeeId,r.articleId,r.period,now);return Object.assign({},r,{consumed:used,remaining:Math.max(0,r.quota-used)});});}
  return{list:list,save:save,getRule:getRule,consumed:consumed,validate:validate,overview:overview};
})();
function lireReglesQuotaContrat(contractId){return ContractQuotaServiceV3.list(contractId);}
function sauvegarderReglesQuotaContrat(contractId,rules,vendeurId){return ContractQuotaServiceV3.save(contractId,rules,vendeurId);}
function obtenirQuotasContrat(contractId,employeeId){return ContractQuotaServiceV3.overview(contractId,employeeId);}
function validerQuotasContrat(contractId,employeeId,articles){var contract=contratsEntreprises().find(function(c){return String(c.id)===String(contractId);});if(!contract)throw new Error('Contrat introuvable.');var employee=lireEmployes(contract.companyId).find(function(e){return String(e.id)===String(employeeId);});if(!employee)throw new Error('Employé introuvable.');return ContractQuotaServiceV3.validate(contract,employee,articles||[],new Date());}
function getContractQuotaRuleForTest(rules,contractId,articleId){return ContractQuotaServiceV3.getRule(rules,contractId,articleId);}
